---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hocs-docs-converter
  labels:
    version: {{.VERSION}}
  annotations:
    downscaler/uptime: {{.UPTIME_PERIOD}}
spec:
  replicas: {{.MIN_REPLICAS}}
  selector:
    matchLabels:
      name: hocs-docs-converter
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-docs-converter
        role: hocs-backend
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      initContainers:
        - name: truststore
          image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.9
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --command=/usr/bin/create-keystore.sh /certs/tls.pem /certs/tls-key.pem /etc/ssl/certs/acp-root.crt
            - --domain=hocs-docs-converter.${KUBE_NAMESPACE}.svc.cluster.local
            - --domain=localhost
            - --onetime=true
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: keystore
              mountPath: /etc/keystore
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 50Mi
              cpu: 100m
      containers:
        - name: certs
          image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.9
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=hocs-docs-converter.${KUBE_NAMESPACE}.svc.cluster.local
            - --expiry=8760h
            - --command=/usr/local/scripts/trigger_nginx_reload.sh
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 50Mi
              cpu: 100m

        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy:v4.2.0
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          env:
            - name: PROXY_SERVICE_HOST
              value: '127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '8080'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: HTTPS_REDIRECT
              value: 'FALSE'
            - name: SERVER_CERT
              value: /certs/tls.pem
            - name: SERVER_KEY
              value: /certs/tls-key.pem
            - name: ADD_NGINX_SERVER_CFG
              value: 'location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
            - name: CLIENT_MAX_BODY_SIZE
              value: '52'
            - name: HTTP2
              value: 'TRUE'
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: secrets
              mountPath: /etc/nginx/secrets
              readOnly: true
          ports:
            - name: https
              containerPort: 10443
          resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 50Mi
              cpu: 100m

        - name: hocs-docs-converter
          image: quay.io/ukhomeofficedigital/hocs-docs-converter:{{.VERSION}}
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          env:
            - name: JAVA_OPTS
              value: '-Xms512m -Xmx1536m -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks -Dhttps.proxyHost=hocs-outbound-proxy.{{.KUBE_NAMESPACE}}.svc.cluster.local -Dhttps.proxyPort=31290 -Dhttp.nonProxyHosts=*.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: JDK_TRUST_FILE
              value: '/etc/keystore/truststore.jks'
            - name: SERVER_PORT
              value: '8080'
          resources:
            limits:
              cpu: 550m
              memory: 2048Mi
            requests:
              cpu: 350m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
              initialDelaySeconds: 15
              periodSeconds: 10
              failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            periodSeconds: 5
          volumeMounts:
            - mountPath: /etc/keystore
              name: keystore
              readOnly: true
      volumes:
        - name: keystore
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: secrets
          emptyDir:
            medium: "Memory"
