---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: checkout
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.1
    commands:
      - git fetch --tags
      - git checkout ${DRONE_TAG}
      - git submodule update --init --recursive

  - name: hocs-converter
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.1
    environment:
      CHART_NAME: hocs-docs-converter
      CHART_VERSION: ^4.0.0
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: hocs-converter
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: ${DRONE_TAG}
    commands:
      - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-docs-converter.yaml
    depends_on:
      - checkout
