---
hocs-generic-service:
  nameOverride: hocs-docs-converter

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-docs-converter
    resources:
      limits:
        memory: 1536Mi
      requests:
        memory: 1536Mi
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=50
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
