apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hocs-docs-converter
  name: hocs-docs-converter
spec:
  maxReplicas: {{.MAX_REPLICAS}}
  minReplicas: {{.MIN_REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hocs-docs-converter
  targetCPUUtilizationPercentage: 50
